from fastapi import FastAPI, Query
from fastapi.responses import JSONResponse

app = FastAPI()

plate_data = {
    "AG6320REK": {
        "result": True,
        "data": [{
            "APM": "",
            "Merk": "HONDA",
            "NoHP": "",
            "NoKK": "",
            "Type": "NF 125TD",
            "Email": ".",
            "NoKTP": ".",
            "NoPIB": "",
            "NoSUT": "",
            "NoTPT": "",
            "Warna": "HITAM",
            "Alamat": "DSN KRAJAN",
            "NoBPKB": "H11041742",
            "NoSRUT": "",
            "NoSTNK": "",
            "NamaBBM": "BENSIN",
            "NoMesin": "JB81E1666871",
            "NoFaktur": "",
            "NoRangka": "MH1JB8117BK670876",
            "NoFormABC": "",
            "Pekerjaan": ".",
            "PlatNomor": "AG-6320-REK",
            "WarnaTNKB": "HITAM",
            "JumlahRoda": 2,
            "IsiCylinder": 125,
            "JumlahSumbu": 1,
            "NamaPemilik": "SUHARYANTO",
            "TanggalSTNK": "2026-05-18",
            "TanglFaktur": None,
            "JenisPemilik": None,
            "TanggalDaftar": "2025-05-14 13:00:18.000000",
            "JenisKendaraan": "SEPEDA MOTOR",
            "KantorBeaCukai": "",
            "TahunPembuatan": 2011,
            "TanggalPengesahan": "2023-05-18",
            "NamaModelKendaraan": "SPD MTR SOLO",
            "TanggalDaftarPertama": None
        }],
        "message": "Data ditemukan"
    },
    "AG2615REK": {
        "result": True,
        "data": [{
            "APM": "",
            "Merk": "HONDA",
            "NoHP": "",
            "NoKK": "",
            "Type": "NC11A 3C AT",
            "Email": "-",
            "NoKTP": "-",
            "NoPIB": "",
            "NoSUT": "",
            "NoTPT": "",
            "Warna": "HITAM SILVER",
            "Alamat": "DSN GEMPOLAN RT02/03",
            "NoBPKB": "Q04463291",
            "NoSRUT": "",
            "NoSTNK": "",
            "NamaBBM": "BENSIN",
            "NoMesin": "JF91E1133235",
            "NoFaktur": "",
            "NoRangka": "MH1JF9110AK134456",
            "NoFormABC": "",
            "Pekerjaan": "-",
            "PlatNomor": "AG-2615-REK",
            "WarnaTNKB": "HITAM",
            "JumlahRoda": "0",
            "IsiCylinder": "110",
            "JumlahSumbu": "0",
            "NamaPemilik": "MUHAMMAD WAHYUDI",
            "TanggalSTNK": "2026-04-05",
            "TanglFaktur": "",
            "JenisPemilik": "",
            "TanggalDaftar": "2023-03-10 10:04:59.000000",
            "JenisKendaraan": "SEPEDA MOTOR",
            "KantorBeaCukai": "",
            "TahunPembuatan": "2010",
            "TanggalPengesahan": "2023-04-05",
            "NamaModelKendaraan": "SPD MTR SOLO",
            "TanggalDaftarPertama": ""
        }],
        "message": "Data ditemukan"
    },
    "AG2956KQ": {
        "result": True,
        "data": [{
            "APM": "",
            "Merk": "SUZUKI",
            "NoHP": "",
            "NoKK": "",
            "Type": "UY125 S AT",
            "Email": "",
            "NoKTP": "",
            "NoPIB": "",
            "NoSUT": "",
            "NoTPT": "",
            "Warna": "HITAM",
            "Alamat": "DS PLOSOREJO RW 08/03",
            "NoBPKB": "5137563J",
            "NoSRUT": "",
            "NoSTNK": "",
            "NamaBBM": "BENSIN",
            "NoMesin": "F484ID158539",
            "NoFaktur": "",
            "NoRangka": "MH8CF48CA7J158178",
            "NoFormABC": "",
            "Pekerjaan": "",
            "PlatNomor": "AG-2956-KQ",
            "WarnaTNKB": "HITAM",
            "JumlahRoda": "2",
            "IsiCylinder": "125",
            "JumlahSumbu": "1",
            "NamaPemilik": "SULISTIYAH",
            "TanggalSTNK": "",
            "TanglFaktur": "2007-06-28",
            "JenisPemilik": "",
            "TanggalDaftar": "2016-06-19 07:30:39.000000",
            "JenisKendaraan": "MB. PENUMPANG",
            "KantorBeaCukai": "",
            "TahunPembuatan": "2007",
            "TanggalPengesahan": "",
            "NamaModelKendaraan": "(TAK DIISI)",
            "TanggalDaftarPertama": ""
        }],
        "message": "Data ditemukan"
    },
    "AG4276RAM": {
        "result": True,
        "data": [{
            "APM": "",
            "Merk": "YAMAHA",
            "NoHP": ".",
            "NoKK": "",
            "Type": "54P CAST WHEEL AT",
            "Email": "-",
            "NoKTP": "3504084806740001",
            "NoPIB": "",
            "NoSUT": "",
            "NoTPT": "",
            "Warna": "MERAH",
            "Alamat": "DSN KRAJAN RT/RW 002/001 KEL. KARANGREJO KEC. KARANGREJO TULUNGAGUNG",
            "NoBPKB": "",
            "NoSRUT": "",
            "NoSTNK": "098824351029",
            "NamaBBM": "BENSIN",
            "NoMesin": "54P1134015",
            "NoFaktur": "",
            "NoRangka": "MH354P20FEJ134048",
            "NoFormABC": "",
            "Pekerjaan": "PERDAGANGAN",
            "PlatNomor": "AG-4276-RAM",
            "WarnaTNKB": "PUTIH",
            "JumlahRoda": "2",
            "IsiCylinder": "113",
            "JumlahSumbu": "1",
            "NamaPemilik": "PATEMAH",
            "TanggalSTNK": "2029-07-21",
            "TanglFaktur": "",
            "JenisPemilik": "",
            "TanggalDaftar": "2024-07-22 09:12:56.000000",
            "JenisKendaraan": "SEPEDA MOTOR",
            "KantorBeaCukai": "",
            "TahunPembuatan": "2014",
            "TanggalPengesahan": "2023-07-21",
            "NamaModelKendaraan": "SPD MTR SOLO",
            "TanggalDaftarPertama": ""
        }],
        "message": "Data ditemukan"
    }
}

@app.get("/plate")
async def get_plate(vrn: str = Query(..., description="Nomor polisi (tanpa strip/spasi)")):
    key = vrn.replace("-", "").upper()
    if key in plate_data:
        return plate_data[key]
    return JSONResponse(status_code=404, content={"result": False, "message": "Data tidak ditemukan"})